"""add_missing_lifecycle_columns

Revision ID: bdab914f9258
Revises: 7457ae6b9f37
Create Date: 2026-03-19 14:30:43.822786+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdab914f9258'
down_revision: Union[str, None] = '7457ae6b9f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_lifecycles', sa.Column('generation', sa.Integer(), nullable=False))
    op.add_column('bot_lifecycles', sa.Column('inherited_traits', sa.JSON(), nullable=False))
    op.add_column('bot_lifecycles', sa.Column('mutations', sa.JSON(), nullable=False))
    op.add_column('bot_lifecycles', sa.Column('relationships', sa.JSON(), nullable=False))
    op.add_column('bot_lifecycles', sa.Column('roles', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_lifecycles', 'roles')
    op.drop_column('bot_lifecycles', 'relationships')
    op.drop_column('bot_lifecycles', 'mutations')
    op.drop_column('bot_lifecycles', 'inherited_traits')
    op.drop_column('bot_lifecycles', 'generation')
    # ### end Alembic commands ###
