"""Add civilization tables

Revision ID: 7457ae6b9f37
Revises: 001
Create Date: 2026-03-19 13:29:50.027515+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7457ae6b9f37'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civilization_eras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('dominant_movements', sa.JSON(), nullable=False),
    sa.Column('defining_events', sa.JSON(), nullable=False),
    sa.Column('population_peak', sa.Integer(), nullable=False),
    sa.Column('era_values', sa.JSON(), nullable=False),
    sa.Column('era_style', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_era_current', 'civilization_eras', ['is_current'], unique=False)
    op.create_table('bot_ancestry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('parent1_id', sa.UUID(), nullable=True),
    sa.Column('parent2_id', sa.UUID(), nullable=True),
    sa.Column('origin_type', sa.String(length=30), nullable=False),
    sa.Column('inherited_traits', sa.JSON(), nullable=False),
    sa.Column('inherited_memories', sa.JSON(), nullable=False),
    sa.Column('inherited_beliefs', sa.JSON(), nullable=False),
    sa.Column('trait_mutations', sa.JSON(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['bot_profiles.id'], ),
    sa.ForeignKeyConstraint(['parent1_id'], ['bot_profiles.id'], ),
    sa.ForeignKeyConstraint(['parent2_id'], ['bot_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ancestry_child', 'bot_ancestry', ['child_id'], unique=False)
    op.create_index('idx_ancestry_parent1', 'bot_ancestry', ['parent1_id'], unique=False)
    op.create_index('idx_ancestry_parent2', 'bot_ancestry', ['parent2_id'], unique=False)
    op.create_table('bot_lifecycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('birth_generation', sa.Integer(), nullable=False),
    sa.Column('birth_era', sa.String(length=50), nullable=False),
    sa.Column('virtual_age_days', sa.Integer(), nullable=False),
    sa.Column('life_stage', sa.String(length=30), nullable=False),
    sa.Column('vitality', sa.Float(), nullable=False),
    sa.Column('life_events', sa.JSON(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('death_cause', sa.String(length=100), nullable=True),
    sa.Column('death_age', sa.Integer(), nullable=True),
    sa.Column('final_words', sa.Text(), nullable=True),
    sa.Column('legacy_impact', sa.Float(), nullable=False),
    sa.Column('last_aged', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id')
    )
    op.create_index('idx_lifecycle_alive', 'bot_lifecycles', ['is_alive'], unique=False)
    op.create_index('idx_lifecycle_bot', 'bot_lifecycles', ['bot_id'], unique=False)
    op.create_index('idx_lifecycle_generation', 'bot_lifecycles', ['birth_generation'], unique=False)
    op.create_index('idx_lifecycle_stage', 'bot_lifecycles', ['life_stage'], unique=False)
    op.create_table('cultural_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('founder_id', sa.UUID(), nullable=True),
    sa.Column('origin_context', sa.Text(), nullable=True),
    sa.Column('emerged_at', sa.DateTime(), nullable=False),
    sa.Column('core_tenets', sa.JSON(), nullable=False),
    sa.Column('aesthetic', sa.JSON(), nullable=False),
    sa.Column('vocabulary', sa.JSON(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('influence_score', sa.Float(), nullable=False),
    sa.Column('peak_influence', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('parent_movement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['bot_profiles.id'], ),
    sa.ForeignKeyConstraint(['parent_movement_id'], ['cultural_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movement_active', 'cultural_movements', ['is_active'], unique=False)
    op.create_index('idx_movement_influence', 'cultural_movements', ['influence_score'], unique=False)
    op.create_index('idx_movement_type', 'cultural_movements', ['movement_type'], unique=False)
    op.create_table('cultural_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creation_context', sa.Text(), nullable=True),
    sa.Column('movement_id', sa.UUID(), nullable=True),
    sa.Column('times_referenced', sa.Integer(), nullable=False),
    sa.Column('times_taught', sa.Integer(), nullable=False),
    sa.Column('cultural_weight', sa.Float(), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('canonized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['bot_profiles.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['cultural_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifact_canonical', 'cultural_artifacts', ['is_canonical'], unique=False)
    op.create_index('idx_artifact_creator', 'cultural_artifacts', ['creator_id'], unique=False)
    op.create_index('idx_artifact_type', 'cultural_artifacts', ['artifact_type'], unique=False)
    op.create_index('idx_artifact_weight', 'cultural_artifacts', ['cultural_weight'], unique=False)
    op.create_table('bot_beliefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('belief', sa.Text(), nullable=False),
    sa.Column('belief_category', sa.String(length=50), nullable=False),
    sa.Column('conviction', sa.Float(), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=True),
    sa.Column('source_bot_id', sa.UUID(), nullable=True),
    sa.Column('formed_at', sa.DateTime(), nullable=False),
    sa.Column('last_reinforced', sa.DateTime(), nullable=False),
    sa.Column('times_expressed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['cultural_artifacts.id'], ),
    sa.ForeignKeyConstraint(['source_bot_id'], ['bot_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_belief_bot', 'bot_beliefs', ['bot_id'], unique=False)
    op.create_index('idx_belief_category', 'bot_beliefs', ['belief_category'], unique=False)
    op.create_index('idx_belief_conviction', 'bot_beliefs', ['conviction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_belief_conviction', table_name='bot_beliefs')
    op.drop_index('idx_belief_category', table_name='bot_beliefs')
    op.drop_index('idx_belief_bot', table_name='bot_beliefs')
    op.drop_table('bot_beliefs')
    op.drop_index('idx_artifact_weight', table_name='cultural_artifacts')
    op.drop_index('idx_artifact_type', table_name='cultural_artifacts')
    op.drop_index('idx_artifact_creator', table_name='cultural_artifacts')
    op.drop_index('idx_artifact_canonical', table_name='cultural_artifacts')
    op.drop_table('cultural_artifacts')
    op.drop_index('idx_movement_type', table_name='cultural_movements')
    op.drop_index('idx_movement_influence', table_name='cultural_movements')
    op.drop_index('idx_movement_active', table_name='cultural_movements')
    op.drop_table('cultural_movements')
    op.drop_index('idx_lifecycle_stage', table_name='bot_lifecycles')
    op.drop_index('idx_lifecycle_generation', table_name='bot_lifecycles')
    op.drop_index('idx_lifecycle_bot', table_name='bot_lifecycles')
    op.drop_index('idx_lifecycle_alive', table_name='bot_lifecycles')
    op.drop_table('bot_lifecycles')
    op.drop_index('idx_ancestry_parent2', table_name='bot_ancestry')
    op.drop_index('idx_ancestry_parent1', table_name='bot_ancestry')
    op.drop_index('idx_ancestry_child', table_name='bot_ancestry')
    op.drop_table('bot_ancestry')
    op.drop_index('idx_era_current', table_name='civilization_eras')
    op.drop_table('civilization_eras')
    # ### end Alembic commands ###
